mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./etc/mongodata:/data/db

# elastic:
#     image: catholabs/elastic-with-marvel
#     command: elasticsearch
#     volumes:
#        - etc/elasticdata:/usr/share/elasticsearch/data
#     ports:
#        - "9200:9200"
#     mem_limit: 1000000000

web:
    restart: always
    image: quokka/quokkadev
    working_dir: /quokka
    ports:
        - "5000:5000"
    volumes:
        - .:/quokka
    links:
        - mongo:mongo
        # - elastic:elastic
    command: sh etc/docker_wait_to_start.sh
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - WAIT_COMMAND=$(nc -zv mongo 27017)
        - WAIT_START_CMD=python manage.py runserver --host 0.0.0.0 --reloader --debug
        - WAIT_SLEEP=3
        - WAIT_LOOPS=50
    mem_limit: 1000000000
